package js.unit.util;

import java.io.Closeable;
import java.io.IOException;

public class Files {
	/**
	 * Close given <code>closeable</code> if not null but ignoring IO exception generated by failing close operation. Please
	 * note that this helper method does not throw {@link IOException} if close operation fails but still record the event to
	 * error logger.
	 * 
	 * @param closeable closeable to close.
	 */
	public static void close(Closeable closeable) {
		if (closeable == null) {
			return;
		}
		try {
			closeable.close();
		} catch (IOException e) {
		} catch (IncompatibleClassChangeError error) {
			try {
				Classes.invoke(closeable, "close");
			} catch (Exception exception) {
			}
		}
	}
}
